sudo: true

env:
  global:
  - PIP_ACCEL_CONFIG=$TRAVIS_BUILD_DIR/pip-accel.conf
  - NO_PREREQ_INSTALL=true
  matrix:
    - PAVER_CMD='help'

language: python

python:
  - "2.7"

# Cannot use travis dependency caching except in their container infrastructure,
# but there you cannot use sudo to install packages. Otherwise we would do
# something like this...
cache:
  apt: true
  directories:
  - $HOME/.pip/download-cache
  - $HOME/.pip-accel

services:
  - mongodb
  - memcached

jdk:
  - openjdk7

rvm:
  - "1.9.3"

before_install:
  - sudo add-apt-repository ppa:chris-lea/node.js -y
  - sudo apt-get update -qq
  - sudo apt-get install gfortran liblapack-dev g++ libxml2-dev libxslt1-dev nodejs gdebi

  # Setup for headless display of browsers
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  # Install pip-accel and other workaround requirements
  - pip install -r requirements/edx/pip-accel.txt

  # There is a bug in pip 1.4.1 by which --exists-action is broken.
  # This is fixed in pip 1.5.x, but alas pip-accel is not yet compatible with pip 1.5.x.
  # Remove when we can upgrade to a version of pip-accel that supports pip 1.5.x.
  - pip install --upgrade "git+https://github.com/jzoldak/pip.git@v1.4.1patch772#egg=pip"

  # Install the edx-platform requirements
  - pip-accel install --exists-action=w -r requirements/edx/pre.txt --verbose

  # Install ruby dependencies
  - bundle install

  # Install node.js dependencies
  - npm install

# command to run tests, e.g. python setup.py test
script:
  - paver $PAVER_CMD

